import mysql.connector

    # Connect to your MySQL server
db = mysql.connector.connect(
        host="localhost",
        user="root",
        password="root"
    )
cursor = db.cursor()

# Create the database
cursor.execute("CREATE DATABASE IF NOT EXISTS calorie_counter")
cursor.execute("USE calorie_counter")

# Create food table
cursor.execute("""
    CREATE TABLE IF NOT EXISTS food (
        food_id INT AUTO_INCREMENT PRIMARY KEY,
        food_name VARCHAR(255) UNIQUE,
        calories INT
    )
""")

# Insert sample data into the food table
food_data = [
    ("Apple", 52),
    ("Banana", 89),
    ("Chicken Breast", 165),
    ("Egg", 70),
    ("Salmon", 208),
    ("Pasta", 131),
    ("Rice", 130),
    ("Broccoli", 31),
    ("Avocado", 160),
    ("Almonds", 7),
    ("Yogurt", 159),
    ("Spinach", 23),
    ("Steak", 271),
    ("Orange", 62),
    ("Milk", 103),
    ("Carrot", 41),
    ("Blueberries", 85),
    ("Potato", 163),
    ("Quinoa", 120),
    ("Turkey Breast", 135),
    ("Honey", 64),
    ("Olive Oil", 119),
    ("Lentils", 230),
    ("Tofu", 94),
    ("Bread", 79),
    ("Peanut Butter", 188),
    ("Green Beans", 31),
    ("Cheese", 113),
    ("Cucumber", 16),
    ("Tomato", 18),
    ("Watermelon", 46),
    ("Beef", 250),
    ("Onion", 40),
    ("Cauliflower", 25),
    ("Chickpeas", 269),
    ("Pineapple", 50),
    ("Coconut Oil", 117),
    ("Shrimp", 85),
    ("Cashews", 155),
    ("Peanuts", 166),
    ("Celery", 6),
    ("Grapes", 69),
    ("Mushrooms", 15),
    ("Soy Milk", 80),
    ("Cheddar Cheese", 402),
    ("Oats", 68),
    ("Asparagus", 20),
    ("Hummus", 166),
    ("Cottage Cheese", 98),
    ("Sardines", 208),
    ("Bell Pepper", 31),
    ("Salad Dressing", 120),
    ("Eggplant", 25),
    ("Sausage", 268),
    ("Cherries", 50),
    ("Salami", 336),
    ("Bacon", 43),
    ("Peaches", 59),
    ("Sour Cream", 193),
    ("Apricots", 48),
    ("Zucchini", 20),
    ("Parmesan Cheese", 122),
    ("Raisins", 299),
    ("Lemon", 17),
    ("Hazelnuts", 628),
    ("Cabbage", 22),
    ("Flour", 364),
    ("Whole Wheat Bread", 247),
    ("Chia Seeds", 486),
    ("Coconut Milk", 230),
    ("Sunflower Seeds", 584),
    ("Feta Cheese", 264),
    ("Popcorn", 382),
    ("Tuna", 144),
    ("Brown Rice", 112),
    ("Walnuts", 654),
    ("Barley", 354),
    ("Pumpkin Seeds", 285),
    ("Cranberries", 46),
    ("Black Beans", 339),
    ("Rye Bread", 259),
    ("Haddock", 90),
    ("Lima Beans", 216),
    ("Pistachios", 562),
    ("Artichoke", 47),
    ("Dates", 282),
    ("Bulgur", 151),
    ("Mozzarella Cheese", 280),
    ("Swiss Cheese", 380),
    ("Macadamia Nuts", 718),
    ("Brussels Sprouts", 43),
    ("Kidney Beans", 333),
    ("Cottage Cheese (Low Fat)", 72),
    ("Gouda Cheese", 356),
    ("Cantaloupe", 34),
    ("Canned Tuna", 116),
    ("Canned Salmon", 165),
    ("Salmon (Smoked)", 117),
    ("Olive Oil (Extra Virgin)", 884),
    ("Beef Jerky", 410),
    ("Chocolate (Dark)", 604),
    ("Poppy Seeds", 525),
    ("White Rice", 129),
    ("Balsamic Vinegar", 88),
    ("Pork", 242),
    ("Sesame Seeds", 573),
    ("Peanut Oil", 884),
    ("Maple Syrup", 260),
    ("Granola", 471),
    ("Soy Sauce", 61),
    ("Honeydew Melon", 36),
    ("Peanut Brittle", 529),
    ("Kale", 49),
    ("Wheat Germ", 338),
    ("Brie Cheese", 334),
    ("Pesto Sauce", 303),
    ("Soybeans", 446),
    ("Couscous", 176),
    ("Fig", 107),
    ("Lentil Soup", 143),
    ("Hamburger", 254),
    ("Corn", 96),
    ("Wheat Bread", 256),
    ("Pork Sausage", 321),
    ("Cornbread", 198),
    ("Cheddar Cheese (Low Fat)", 173),
    ("Beef Stew", 155),
    ("Cereal", 379),
    ("Pork Chop", 185),
    ("Guacamole", 140),
    ("Bagel", 289),
    ("Pita Bread", 275),
    ("Cornflakes", 363),
    ("Muesli", 289),
    ("Pork Ribs", 369),
    ("Shredded Wheat", 210),
    ("Cauliflower Rice", 25),
    ("Cabbage Soup", 33),
    ("Pumpkin Pie", 243),
    ("Beef Steak", 219),
    ("Rice Cake", 35),
    ("Beef Ribs", 318),
    ("Chicken Soup", 63),
    ("Taco Shell", 57),
    ("Gingerbread", 343),
    ("Chicken Leg", 209),
    ("Chicken Thigh", 250),
    ("Chicken Wing", 203),
    ("Oyster Sauce", 19),
    ("Clam", 86),
    ("Lobster", 89),
    ("Crab", 83),
    ("Caviar", 264),
    ("Octopus", 82),
    ("Calamari", 80),
    ("Mussels", 73),
    ("Scallops", 69),
    ("Breaded Fish", 273),
    ("Fried Fish", 232),
    ("Fish Fillet", 124),
    ("Fish Stick", 237),
    ("Sushi", 129),
    ("Nori Seaweed", 7),
    ("Ramen Noodles", 188),
    ("Udon Noodles", 151),
    ("Soba Noodles", 113),
    ("Egg Noodles", 138),
    ("Spaghetti", 157),
    ("Fusilli Pasta", 154),
    ("Macaroni Pasta", 159),
    ("Lasagna", 133),
    ("Ravioli", 93),
    ("Tortellini", 101),
    ("Fettuccine", 210),
    ("Pizza", 266),
    ("Cheeseburger", 303),
    ("Hamburger (Fast Food)", 295),
    ("Hot Dog", 151),
    ("Fried Chicken", 266),
    ("Chicken Nuggets", 300),
    ("French Fries", 312),
    ("Onion Rings", 403),
    ("Potato Chips", 536),
    ("Pretzels", 386),
    ("Corn Chips", 509),
    ("Popcorn (Microwaved)", 387),
    ("Nachos", 393),
    ("Salsa", 36),
    ("Tartar Sauce", 120),
    ("Mayonnaise", 680),
    ("Ketchup", 101),
    ("Barbecue Sauce", 234),
    ("Teriyaki Sauce", 89),
    ("Soybean Paste", 198),
    ("Worcestershire Sauce", 66),
    ("Tabasco Sauce", 27),
    ("Hollandaise Sauce", 357),
    ("Tzatziki", 59),
    ("Ranch Dressing", 457),
    ("Blue Cheese Dressing", 321),
    ("Caesar Dressing", 283),
    ("Thousand Island Dressing", 350),
    ("Italian Dressing", 266),
    ("French Dressing", 373),
    ("Russian Dressing", 344),
    ("Catalina Dressing", 286),
    ("Honey Mustard Dressing", 318),
    ("Balsamic Vinaigrette", 323),
    ("Peanut Sauce", 350),
    ("Sour Cream Dip", 130),
    ("Guacamole Dip", 152),
    ("Hummus Dip", 177),
    ("Bean Dip", 117),
    ("Taramasalata Dip", 180),
    ("Spinach Dip", 150),
    ("Cheese Dip", 194),
    ("Salsa Dip", 36),
    ("Clam Dip", 150),
    ("Crab Dip", 170),
    ("Chili Dip", 168),
    ("Buffalo Chicken Dip", 319),
    ("Queso Dip", 162),
    ("Fondue", 224),
    ("Chocolate Fondue", 313),
    ("Caramel Sauce", 322),
    ("Butterscotch Sauce", 332),
    ("Chocolate Syrup", 180),
    ("Ice Cream", 207),
    ("Frozen Yogurt", 159),
    ("Sorbet", 96),
    ("Gelato", 200),
    ("Sherbet", 144),
    ("Milkshake", 175),
    ("Smoothie", 125),
    ("Chocolate Milk", 190),
    ("Eggnog", 135),
    ("Hot Chocolate", 192),
    ("Coffee", 2),
    ("Tea", 0),
    ("Green Tea", 1),
    ("Black Tea", 1),
    ("Herbal Tea", 0),
    ("Fruit Tea", 1),
    ("Milk Tea", 43),
    ("Bubble Tea", 160),
    ("Iced Tea", 31),
    ("Cola", 105),
    ("Soda", 44),
    ("Lemonade", 99),
    ("Orange Juice", 45),
    ("Apple Juice", 45),
    ("Grape Juice", 60),
    ("Cranberry Juice", 46),
    ("Tomato Juice", 17),
    ("Pineapple Juice", 53),
    ("Carrot Juice", 39),
    ("Coconut Water", 19),
    ("Almond Milk", 17),
    ("Soy Milk", 80),
    ("Rice Milk", 47),
    ("Oat Milk", 50),
    ("Cashew Milk", 25),
    ("Hazelnut Milk", 28),
    ("Coconut Milk", 230),
    ("Hemp Milk", 70),
    ("Flax Milk", 50),
    ("Quinoa Milk", 48),
    ("Macadamia Milk", 50),
    ("Camel Milk", 50),
    ("Donkey Milk", 60),
    ("Yak Milk", 60),
    ("Buffalo Milk", 97),
    ("Sheep Milk", 108),
    ("Goat Milk", 168),
    ("Horse Milk", 195),
    ("Moose Milk", 213),
    ("Deer Milk", 290),
    ("Reindeer Milk", 323),
    ("Zebra Milk", 360),
    ("Llama Milk", 360),
    ("Kangaroo Milk", 445),
    ("Elephant Milk", 500),
    ("Whale Milk", 500),
    ("Dolphin Milk", 500),
    ("Seal Milk", 570),
    ("Walrus Milk", 780),
    ("Penguin Milk", 780),
    ("Polar Bear Milk", 1200),
    ("Panda Milk", 1300),
    ("Giraffe Milk", 1300),
    ("Tiger Milk", 1200),
    ("Lion Milk", 1600),
    ("Leopard Milk", 1600),
    ("Cheetah Milk", 1600),
    ("Panther Milk", 1600),
    ("Cougar Milk", 1600),
    ("Jaguar Milk", 1600),
    ("Bobcat Milk", 1600),
    ("Ocelot Milk", 1600),
    ("Lynx Milk", 1600),
    ("Serval Milk", 1600),
    ("Caracal Milk", 1600),
    ("Fishing Cat Milk", 1600),
    ("Leopard Cat Milk", 1600),
    ("Rusty Spotted Cat Milk", 1600),
    ("Pallas's Cat Milk", 1600),
    ("Sand Cat Milk", 1600),
    ("Black-Footed Cat Milk", 1600),
    ("African Wildcat Milk", 1600),
    ("European Wildcat Milk", 1600),
    ("Arabian Wildcat Milk", 1600),
    ("Jungle Cat Milk", 1600),
    ("Asian Golden Cat Milk", 1600),
    ("Bay Cat Milk", 1600),
    ("Marbled Cat Milk", 1600),
    ("Flat-Headed Cat Milk", 1600),
    ("Bornean Clouded Leopard Milk", 1600),
    ("Sunda Clouded Leopard Milk", 1600),
    ("Neofelis Nebulosa Milk", 1600),
    ("Neofelis Diardi Milk", 1600),
    ("Snow Leopard Milk", 1600),
    ("Tiger Cat Milk", 1600),
    ("Golden Tiger Milk", 1600),
    ("Maltese Tiger Milk", 1600),
    ("Bengal Tiger Milk", 1600),
    ("Indo-Chinese Tiger Milk", 1600),
    ("Siberian Tiger Milk", 1600),
    # Add more sample food items here
]

cursor.executemany("INSERT IGNORE INTO food (food_name, calories) VALUES (%s, %s)", food_data)

# Create user_list table
cursor.execute("""
    CREATE TABLE IF NOT EXISTS user_list (
        user_id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE,
        password VARCHAR(255)
    )
""")

# Commit changes and close connection
db.commit()
cursor.close()
db.close()